replicaCount: 1

image:
  repository: ghcr.io/mibber123/catalog
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

ingress:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"

nameOverride: ""
fullnameOverride: books-catalog

loadSecretsFrom: books-database-postgresql

environmentVariables:
  - name: DATABASE_USER
    value: books

  - name: DATABASE_NAME
    value: books

  - name: DATABASE_HOST
    value: books-database-postgresql-0.books-database-postgresql-hl.default.svc.cluster.local

  - name: DEVELOPMENT_MODE
    value: "false"
