apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.migrationJobName" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      {{ include "app.imagePullSecrets" . | nindent 6 }}
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ include "app.image" . }}"
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: {{ include "app.configMapName" . }}
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.databaseSecretName" . }}
                  key: password
