# -----------------------------------------------------------------------------
# Application
# -----------------------------------------------------------------------------

application:
  replicas: 3
  port: 8000

# -----------------------------------------------------------------------------
# Container Image
# -----------------------------------------------------------------------------

image:
  repository: ghcr.io/mibber123/catalog
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------

database:
  host: books-database-postgresql-0.books-database-postgresql-hl.default.svc.cluster.local
  name: books
  user: books
  secretName: books-database-postgresql

# -----------------------------------------------------------------------------
# Service
# -----------------------------------------------------------------------------

service:
  type: ClusterIP
  port: 80

# -----------------------------------------------------------------------------
# Ingress
# -----------------------------------------------------------------------------

ingress:
  enabled: true

  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"

  path: /api
  pathType: Prefix

# -----------------------------------------------------------------------------
# Resources
# -----------------------------------------------------------------------------

resources:
  requests:
    cpu: "500m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "256Mi"

# -----------------------------------------------------------------------------
# Environment Variables
# -----------------------------------------------------------------------------

environment:
  DEVELOPMENT_MODE: "false"
