apiversion: batch/v1
kind: Job
metadata:
    name: "{{ .Release.Name}}-migrate"
    annotations:
        helm.sh/hook: pre-install, pre-upgrade
        helm.sh/hook-weight: "0"
        helm.sh/hook-delete-policy: before-hook-creation

spec:
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    restartPolicy: Never
    Containers:
    - name: migrate
      image:
      command: {""}
      envFrom:
      - configMapRef:
        name: {{}}

    env:
    - name: DATABASE_PASSWORD
    valueFrom:
    secretKeyRef:
    name: {{ .Values.loadSecretsFrom }}
    key: password
